### ISSUE TITLE
game center not launching

### ISSUE THREAD

**Issue by moh1122** [gamechina/GrubbyWorm#1]
Hello
Thank you for the great game tutorial
Btw game center is not launching when i open the app.
I even installed it on my iphone not only the simulator and still the game center not launching, any clue?
Can I use part of your app as im building a similar game.
Thank you

**Comment by Evilcome** [comment]
@moh1122 
Thanks, it's great you like it. 
Game Center works well on my phone and simulator. It is powered by [Easy Game Center Swift](https://github.com/DaRkD0G/Easy-Game-Center-Swift), In `GameViewController.swift` file I use the following code to init the game center:

```
/*** Set Delegate UIViewController ***/
EasyGameCenter.sharedInstance(self)

....

/*** Set View Controller delegate, that's when you change UIViewController ***/
EasyGameCenter.delegate = self
```

And then, in `easyGameCenterAuthentified` delegate method, I enabled the ui game center button. You can try again, add `EasyGameCenter.debugMode = true` under `EasyGameCenter.sharedInstance(self)`, and there will print some useful logs, maybe helpful for you.

You can use any part in this project for your own game, even the images. Happy coding and sharing.

**Comment by Evilcome** [comment]
@moh1122 
Additional, clone the latest version of the project please, I've seen your name in the game center(sandbox) global leaderboard with 100 score. This should because of my old test code, so you should already got game center works well.

**Comment by Evilcome** [comment]
🐜I'll close this issue, if have any problem, reopen it.

**Comment by moh1122** [comment]
hello
I cloned the latest version
game center is not launching when I enter the game and the logo is greyed out ?

**Comment by moh1122** [comment]
What I mean is that the logo is disabled, how can I make it to normal state?
