### ISSUE TITLE
UIAlertController

### ISSUE THREAD

**Issue by moh1122** [gamechina/GrubbyWorm#4]
Hey
Hope your ok
Well im trying to make a uialertcontroller in viewdidload from the gameviewcontroller but unfortunately its not appearing do you have any clue how to add an alert controller to your project.
Thank you on advance.

**Comment by moh1122** [comment]
i hope you can help me with this
Thnk you

**Comment by Evilcome** [comment]
yes, I'd like to. Can you write some code here about the uialertcontroller, I want to see how you do it~

**Comment by moh1122** [comment]
Hello,
Please find my code below, that's what i want to use. I'm putting it in gameviewcontroller.swift in overide func viewdidload() but its not working it builds normally without errors but my alertcontroller wont show up. Any clue? Thank you

func Alert(){  
   //Create the AlertController
      let actionSheetController: UIAlertController = UIAlertController(title: "Test", message: "To access this game you need to press the bellow buttons.", preferredStyle: .Alert)

```
  //Create and an option action
    let downLoadAction: UIAlertAction = UIAlertAction(title: "Download ", style: .Default) { action -> Void in
        //Do some other stuff
        var url : NSURL
        url = (NSURL(string: "https://itunes.apple.com/ ")!)
        UIApplication.sharedApplication().openURL(url)

    }

    actionSheetController.addAction(downLoadAction)

    //Create and an option action
    let Apps: UIAlertAction = UIAlertAction(title: " Apps on the AppStore", style: .Default) { action -> Void in
        //Do some other stuff
        var url : NSURL
        url = (NSURL(string: "https://itunes.apple.com/ ")!)
        UIApplication.sharedApplication().openURL(url)

    }
    actionSheetController.addAction(Apps)
    //Present the AlertController
    self.presentViewController(actionSheetController, animated: true, completion: nil)

}
```

}

**Comment by Evilcome** [comment]
hi, I think you just define the function, but never call it.
you can try like this:

```
override func viewDidLoad() {
    super.viewDidLoad()
    ......
}

func alert() {
//Create the AlertController
        let actionSheetController: UIAlertController = UIAlertController(title: "Test", message: "To access this game you need to press the bellow buttons.", preferredStyle: .Alert)

        //Create and an option action
        let downLoadAction: UIAlertAction = UIAlertAction(title: "Download ", style: .Default) { action -> Void in
            //Do some other stuff
            var url : NSURL
            url = (NSURL(string: "https://itunes.apple.com/ ")!)
            UIApplication.sharedApplication().openURL(url)

        }

        actionSheetController.addAction(downLoadAction)

        //Create and an option action
        let Apps: UIAlertAction = UIAlertAction(title: " Apps on the AppStore", style: .Default) { action -> Void in
            //Do some other stuff
            var url : NSURL
            url = (NSURL(string: "https://itunes.apple.com/ ")!)
            UIApplication.sharedApplication().openURL(url)

        }
        actionSheetController.addAction(Apps)
        //Present the AlertController
        self.presentViewController(actionSheetController, animated: true, completion: nil)
}

```

then in viewDidAppear or other opportunity(maybe some button tapped):

```
override func viewDidAppear(animated: Bool) {
        super.viewDidAppear(animated)

        /*** Set View Controller delegate, that's when you change UIViewController ***/
        EasyGameCenter.delegate = self

        // call alert function!
        alert()
    }
```

you may get the below effect:
<img width="500" alt="alert" src="https://cloud.githubusercontent.com/assets/7099792/11262206/64b3bd0c-8eb7-11e5-852d-a27652be15ae.png">

**Comment by moh1122** [comment]
Thank you man
its working with me now.

**Comment by moh1122** [comment]
Im using the same thing on the help button its not working 
can i call a function from another class?

**Comment by Evilcome** [comment]
yes, of course. You should get the GameViewController class in the how button tapped scope. like:

```
// save the game view controller reference in Game Class, you should change the init function of Game Class.
override func viewDidLoad() {
        super.viewDidLoad()

        // Configure the view.
        let skView = self.view as! SKView
        skView.showsFPS = true
        skView.showsNodeCount = true
        skView.showsDrawCount = true
        skView.showsFields = true
        skView.showsQuadCount = true

        game = Game(view: skView, controller: self)
        ......
    }

// when how button tapped
howButton.actionTouchUpInside = GWButtonTarget.aBlock({ () -> Void in
            print("click how")
            self._game.controller.presentViewController(........)
        })
```

or use the rootViewController. like:

```
self._game._view.window?.rootViewController?.presentViewController(........)
```

if you do like this, you may remove `_view` property `private` statement, make it public.

**Comment by moh1122** [comment]
thnks for your quick reply:
im facing a couple of errors i added:
        game = Game(view: skView, controller: self)
in GameViewCntroller.swift 
im getting an error saying (extra argument controller in call)
any clue?

**Comment by Evilcome** [comment]
yes, you should modify the init function of Game Class. in Game.swift:

```
var controller: UIViewController?

init(view: SKView, controller: UIViewController?) {
    self.controller = controller
}
```

**Comment by moh1122** [comment]
thanks man for your help i modified the init function
and its no giving errors but when im adding:
            self._game.controller.presentViewController(........)
im getting errors can you plz let me know wht shall be replaced in (.........) so my build will succeed.
Thank you

**Comment by Evilcome** [comment]
I mean you should put the `actionSheetController, animated: true, completion: nil` in the (.........), and the `actionSheetController` should be created before as you write at the beginning.

**Comment by moh1122** [comment]
thnk you man :+1:
