### ISSUE TITLE
Enable Game Center

### ISSUE THREAD

**Issue by moh1122** [gamechina/GrubbyWorm#5]
Hello
I'm working on a separate game and i want to add gamecenter to it like your app here.
Ill copy EasyGameCenter.swift and paste it in my app then call it in viewdidload.
Am I on the right track or i should something else.
Thank you

**Comment by Evilcome** [comment]
Read this please:
https://github.com/DaRkD0G/Easy-Game-Center-Swift#initialize-and-example
