### ISSUE TITLE
Enable Leaderboard in gamecenter

### ISSUE THREAD

**Issue by moh1122** [gamechina/GrubbyWorm#6]
Hello
How you doing,
can you please help me in submitting the score to gamecenter as a leader board I'v already done a leaderboard id in iTunes connect? Shall i do anything else from the project side.
Thank you
Awaiting your reply.

**Comment by Evilcome** [comment]
you can call below code when you want to report the score:

```
EasyGameCenter.reportScoreLeaderboard(leaderboardIdentifier: "your leaderboard id", score: score)
```

**Comment by moh1122** [comment]
Thank you man your awesome :) :+1:
