### ISSUE TITLE
app crashing

### ISSUE THREAD

**Issue by moh1122** [gamechina/GrubbyWorm#7]
hello 
after updating to ios 9.2 the app is crashing.
Any clue?

**Comment by Evilcome** [comment]
I'll check, thanks for report.

**Comment by moh1122** [comment]
thnk u for your concern

**Comment by Evilcome** [comment]
Issue found, it seems a spritekit bug. You can just remove the below code in file `GameViewController`:

```
skView.showsFields = true
```

There will no memory issue, and no crash. Thanks again for reporting.
